# D:\city_chain_project\DAGs\libs\algorithm\poh_types\poh_types\exceptions.py
class PoHTypesError(Exception):
    """poh_types 内で発生する例外"""
    pass
